---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pihole-repo
  namespace: pihole-system
spec:
  interval: 1m0s
  url: https://mojo2600.github.io/pihole-kubernetes/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami-repo
  namespace: pihole-system
spec:
  interval: 1m0s
  url: https://charts.bitnami.com/bitnami
